### ISSUE TITLE
Test data set

### ISSUE THREAD

**Issue by pvepamb1** [pvepamb1/menu-manager#2]

**Comment by adhinag1** [comment]
Attached link for sample test dataset. 
https://jsoneditoronline.org/?id=dfca995e957842cd998480a345559a2f

**Comment by adhinag1** [comment]
[Test_dataset.json](https://app.gitkraken.com/api/glo/boards/5bb1bb6a8586640e005827e9/attachments/5bb30b4954d8310e00665eeb)
